[2022-02-01 12:58:39,471] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2022-02-01 12:58:39,494] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2022-02-01 12:58:39,495] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 12:58:39,496] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-01 12:58:39,497] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 12:58:39,591] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_data_task> on 2019-04-01 00:00:00+00:00
[2022-02-01 12:58:39,596] {standard_task_runner.py:52} INFO - Started process 7616 to run task
[2022-02-01 12:58:39,601] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_fhv_dag', 'download_data_task', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_fhv_dag.py', '--cfg-path', '/tmp/tmpy99_v6ju', '--error-file', '/tmp/tmpytsyqg_d']
[2022-02-01 12:58:39,603] {standard_task_runner.py:77} INFO - Job 10: Subtask download_data_task
[2022-02-01 12:58:39,744] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-04-01T00:00:00+00:00 [running]> on host 153a4cabbd26
[2022-02-01 12:58:39,857] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-01 12:58:39,944] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_fhv_dag
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2022-02-01 12:58:39,945] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-01 12:58:39,946] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-04.csv > /opt/***/fhv_tripdata_2019-04.csv']
[2022-02-01 12:58:39,955] {subprocess.py:85} INFO - Output:
[2022-02-01 12:59:31,364] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-02-01 12:59:31,367] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 7616. PIDs of all processes in the group: [7619, 7620, 7616]
[2022-02-01 12:59:31,367] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 7616
[2022-02-01 12:59:31,368] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-01 12:59:31,368] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-02-01 12:59:31,460] {process_utils.py:70} INFO - Process psutil.Process(pid=7619, status='terminated', started='12:58:39') (7619) terminated with exit code None
[2022-02-01 12:59:31,461] {process_utils.py:70} INFO - Process psutil.Process(pid=7620, status='terminated', started='12:58:39') (7620) terminated with exit code None
[2022-02-01 12:59:31,462] {process_utils.py:70} INFO - Process psutil.Process(pid=7616, status='terminated', exitcode=0, started='12:58:38') (7616) terminated with exit code 0
[2022-02-01 13:06:08,407] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2022-02-01 13:06:08,418] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2022-02-01 13:06:08,418] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 13:06:08,419] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-01 13:06:08,419] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-01 13:06:08,492] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_data_task> on 2019-04-01 00:00:00+00:00
[2022-02-01 13:06:08,497] {standard_task_runner.py:52} INFO - Started process 8649 to run task
[2022-02-01 13:06:08,501] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_fhv_dag', 'download_data_task', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_fhv_dag.py', '--cfg-path', '/tmp/tmpycxwu11f', '--error-file', '/tmp/tmpb2at5xip']
[2022-02-01 13:06:08,503] {standard_task_runner.py:77} INFO - Job 20: Subtask download_data_task
[2022-02-01 13:06:08,626] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_fhv_dag.download_data_task scheduled__2019-04-01T00:00:00+00:00 [running]> on host 153a4cabbd26
[2022-02-01 13:06:08,770] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-01 13:06:08,832] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_fhv_dag
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2022-02-01 13:06:08,834] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-01 13:06:08,835] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-04.csv > /opt/***/fhv_tripdata_2019-04.csv']
[2022-02-01 13:06:08,844] {subprocess.py:85} INFO - Output:
[2022-02-01 13:10:10,419] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-01 13:10:10,950] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_fhv_dag, task_id=download_data_task, execution_date=20190401T000000, start_date=20220201T130608, end_date=20220201T131010
[2022-02-01 13:10:11,445] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-01 13:10:11,797] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
